name: "Rubocop"

on:
  pull_request:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Rubocop
        uses: hoovad/rubocop-action@f6dbe8d535ff0f1e5820c6584d827cf0630fc293 # v0.0.4
